apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kongeelabs.home.arpa
  namespace: kong
spec:
  secretName: kong-tls
  commonName: kongeelabs.home.arpa
  dnsNames:
  - "kongeelabs.home.arpa"
  - "portal.kongeelabs.home.arpa"
  - "manager.kongeelabs.home.arpa"
  - "*.kongeelabs.home.arpa"
  - "a29948c58d0e0404190565a02f30cb8d-ae08b15f09445686.elb.us-east-1.amazonaws.com"
  - "a3a97e5a46ff54ac2a18210e7f30faf3-4a41aa396b5a5a18.elb.us-east-1.amazonaws.com"
  renewBefore: 360h
  duration: 2160h
  isCA: false
  issuerRef:
    name: certman-selfsigned-issuer
    kind: ClusterIssuer
