apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong.hbfs.io
  namespace: kong
spec:
  secretName: kong-tls
  commonName: kong.hbfs.io
  dnsNames:
  - "kong.hbfs.io"
  - "admin.kong.hbfs.io"
  - "manager.kong.hbfs.io"
  - "*.kong.hbfs.io"
  renewBefore: 360h
  duration: 2160h
  isCA: false
  issuerRef:
    name: certman-selfsigned-issuer
    kind: ClusterIssuer
