# REFERENCES:
# https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md#postgresql-parameters
# https://engineering.bitnami.com/articles/create-a-production-ready-postgresql-cluster-bitnami-kubernetes-and-helm.html
nameOverride: ""
fullnameOverride: ""

global:
  storageClass: "ceph-block"
  postgresql:
    servicePort: "5432"
    postgresqlDatabase: "kong"
    postgresqlUsername: "kong"
    postgresqlPassword: "kong"
    replicationPassword: "kong_repl_user"

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0

psp:
  create: false
rbac:
  create: false
serviceAccount:
  enabled: false
  autoMount: false
  name: ""

replication:
  enabled: true
  user: kong_repl_user
  password: kong_repl_password
  readReplicas: 1
  synchronousCommit: "off"
  numSynchronousReplicas: 0
  applicationName: kong
  singleService: true
  uniqueServices: false

postgresqlDatabase: "kong"
postgresqlUsername: postgres
postgresqlPassword: "postgres_password"
postgresqlPostgresPassword: "postgres_admin_password"

service:
  type: LoadBalancer
  port: 5432
  loadBalancerIP: ""
  annotations: {}

shmVolume:
  enabled: true
  chmod:
    enabled: true
  sizeLimit: ""

persistence:
  enabled: true
  size: 8Gi
  storageClass: "ceph-block"
  mountPath: /bitnami/postgresql
  existingClaim: ""
  annotations: {}
  accessModes:
    - ReadWriteOnce
  subPath: ""

updateStrategy:
  type: RollingUpdate

primary:
  annotations: {}
  podAntiAffinityPreset: soft
  service:
    type: "LoadBalancer"

readReplicas:
  annotations: {}
  podAntiAffinityPreset: soft
  service:
    type: "LoadBalancer"
  persistence:
    enabled: true

resources:
  requests:
    memory: 256Mi
    cpu: 250m

networkPolicy:
  enabled: true
  allowExternal: true

tls:
  enabled: false
  autoGenerated: false
  preferServerCiphers: true

metrics:
  enabled: false
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
